version: '3.1'

services:
  db:
    image: migration_mysql
    build: 
      context: .
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  server:
    image: nodejs
    volumes:
      - ./server:/server
      - /server/node_modules
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - PORT=8000
    command: node app.js
    depends_on:
      - db

  react:
    image: react
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_PORT=8000
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - server
    command: npm start
